"""empty message

Revision ID: 171747dccec3
Revises: 
Create Date: 2023-10-10 22:01:43.627350

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '171747dccec3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('username', sa.String(length=20), nullable=False),
                    sa.Column('password', sa.String(length=20), nullable=False),
                    sa.Column('email', sa.String(length=20), nullable=False),
                    sa.Column('join_time', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
